# Generated by Django 5.1 on 2024-08-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_contribution_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='first_sentence',
            field=models.TextField(default='No sentence provided'),
        ),
    ]
